apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: buenzli-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: backend
          image: ghcr.io/j4n06/buenzli-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: JWT_SECRET
            - name: MAIL_SERVICE_URL
              value: "http://mailservice:4000"
