# k8s/mailservice.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailservice
  namespace: buenzli-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailservice
  template:
    metadata:
      labels:
        app: mailservice
    spec:
      containers:
        - name: mailservice
          image: your-dockerhub/buenzli-mailservice:latest
          ports:
            - containerPort: 4000
          env:
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: SMTP_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: mailservice
  namespace: buenzli-shop
spec:
  selector:
    app: mailservice
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP