# k8s/backend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: buenzli-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub/buenzli-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: buenzli-secrets
                  key: JWT_SECRET
            - name: MAIL_SERVICE_URL
              value: "http://mailservice:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: buenzli-shop
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
