name: Deploy Robot Shop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install kubernetes
          ansible-galaxy collection install kubernetes.core community.kubernetes

      - name: Setup kubeconfig with public IP substitution
        run: |
          mkdir -p /home/runner/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > /home/runner/.kube/config
          sed -i "s/K8S_MASTER_PUBLIC_IP/${{ secrets.K8S_MASTER_PUBLIC_IP }}/g" /home/runner/.kube/config
          chmod 600 /home/runner/.kube/config

      - name: Debug kubeconfig content (optional)
        run: head -20 /home/runner/.kube/config

      - name: Test Kubernetes connection
        run: kubectl get nodes
        env:
          KUBECONFIG: /home/runner/.kube/config

      - name: Deploy Robot Shop with Ansible
        run: |
          ansible-playbook ansible/deploy_robotshop.yaml -i ansible/inventory_robotshop.ini
        env:
          KUBECONFIG: /home/runner/.kube/config
