# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: buenzli-secrets
  namespace: buenzli-shop
stringData:
  DATABASE_URL: "postgres://user:passwort@postgres:5432/buenzlishop"
  JWT_SECRET: "supergeheim"
  SMTP_HOST: "smtp.mailtrap.io"
  SMTP_PORT: "587"
  SMTP_USER: "dein-user"
  SMTP_PASS: "dein-pass"