- name: Deaktiviere Swap sofort
  command: swapoff -a

- name: Deaktiviere Swap persistent
  replace:
    path: /etc/fstab
    regexp: '^\s*(\S+)\s+swap\s+(\S+)\s+.*$'
    replace: '# \1 swap \2'

- name: Kernel-Module persistent konfigurieren
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Kernel-Module laden
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Sysctl-Einstellungen setzen
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Sysctl anwenden
  command: sysctl --system

- name: Notwendige Pakete installieren
  apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: true
