apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: medusa
  template:
    metadata:
      labels:
        app: medusa
    spec:
      containers:
      - name: medusa
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: "{{ .Values.env.DATABASE_URL }}"
        - name: REDIS_URL
          value: "{{ .Values.env.REDIS_URL }}"
