- name: Add Kubernetes APT GPG key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/kubernetes-apt-key.gpg
    mode: "0644"
  become: true

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  become: true

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Kubernetes components
  ansible.builtin.apt:
    name:
      - containerd
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_output
  args:
    creates: /etc/kubernetes/admin.conf

- name: Copy admin.conf to ubuntu user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Extract join command
  shell: |
    echo "{{ kubeadm_output.stdout_lines | join('\n') }}" | grep -A 2 'kubeadm join' > /home/ubuntu/join-command.sh
    chmod +x /home/ubuntu/join-command.sh
