- name: Install containerd & kubeadm
  become: true
  shell: |
    apt-get update
    apt-get install -y containerd
    modprobe overlay
    modprobe br_netfilter
    echo -e "overlay\nbr_netfilter" >> /etc/modules-load.d/k8s.conf
    echo -e "net.bridge.bridge-nf-call-iptables=1\nnet.ipv4.ip_forward=1" >> /etc/sysctl.d/k8s.conf
    sysctl --system
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubelet kubeadm kubectl
    kubeadm init --pod-network-cidr=10.244.0.0/16 | tee /root/kubeadm_output.txt

- name: Debug kubeadm output
  become: true
  shell: cat /root/kubeadm_output.txt
  register: kubeadm_debug
  ignore_errors: true

- name: Print kubeadm init result
  debug:
    var: kubeadm_debug.stdout

- name: Fail if admin.conf is missing
  become: true
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf

- name: Stop if kubeadm failed
  fail:
    msg: "kubeadm init scheint fehlgeschlagen zu sein: admin.conf fehlt!"
  when: not admin_conf.stat.exists

- name: Save kubeconfig for ubuntu user
  become: true
  shell: |
    mkdir -p /home/ubuntu/.kube
    cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    chown ubuntu:ubuntu /home/ubuntu/.kube/config
  args:
    executable: /bin/bash

- name: Export join command
  become: true
  shell: |
    grep -A 2 "kubeadm join" /root/kubeadm_output.txt > /home/ubuntu/join-command.sh
    chmod +x /home/ubuntu/join-command.sh
  args:
    executable: /bin/bash
