- name: Install containerd & kubeadm
  shell: |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y containerd
    modprobe overlay
    modprobe br_netfilter
    echo -e "overlay\nbr_netfilter" > /etc/modules-load.d/k8s.conf
    echo -e "net.bridge.bridge-nf-call-iptables=1\nnet.ipv4.ip_forward=1" > /etc/sysctl.d/k8s.conf
    sysctl --system
    swapoff -a
    sed -i.bak '/ swap / s/^/#/' /etc/fstab
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubelet kubeadm kubectl
  args:
    warn: false

- name: Init Kubernetes master
  become: true
  shell: |
    kubeadm init --pod-network-cidr=10.244.0.0/16 > /root/kubeadm_output.txt 2>&1
  register: kubeadm_result
  failed_when: kubeadm_result.rc != 0

- name: Debug kubeadm init output
  become: true
  shell: cat /root/kubeadm_output.txt
  register: kubeadm_output_raw
  ignore_errors: true

- name: Show kubeadm init output
  debug:
    var: kubeadm_output_raw.stdout_lines

- name: Save kubeconfig for ubuntu user
  become: true
  shell: |
    mkdir -p /home/ubuntu/.kube
    cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    chown ubuntu:ubuntu /home/ubuntu/.kube/config
  when: kubeadm_result.rc == 0

- name: Export join command
  become: true
  shell: |
    grep -A 2 "kubeadm join" /root/kubeadm_output.txt > /home/ubuntu/join-command.sh
    chmod +x /home/ubuntu/join-command.sh
  when: kubeadm_result.rc == 0
