---
- name: Deploy Stan's Robot Shop via Helm
  hosts: robotshop
  gather_facts: no

  vars:
    namespace: three-tier
    release_name: three-tier-app
    chart_path: ./charts/robotshop
    values_file: ./charts/robotshop/values.yaml

  tasks:
    - name: Ensure Kubernetes namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present

    - name: Deploy Robot Shop via Helm
      community.kubernetes.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_path }}"
        release_namespace: "{{ namespace }}"
        create_namespace: false
        values_file: "{{ values_file }}"
        state: present
