- name: Vorbereitung auf allen Nodes (Common Setup)
  become: true
  hosts: all
  roles:
    - common

- name: Kubernetes Master initialisieren
  become: true
  hosts: master
  roles:
    - master

- name: Worker dem Cluster beitreten lassen
  become: true
  hosts: worker
  roles:
    - worker
