- name: Vorbereitung auf allen Nodes (Common Setup)
  hosts: all
  become: yes

  roles:
    - common

- name: Kubernetes Master initialisieren
  hosts: master
  become: yes

  roles:
    - master

- name: Worker dem Cluster beitreten lassen
  hosts: worker
  become: yes

  roles:
    - worker

  name: Run Ansible Playbook
  run: |
    sudo apt-get update
    sudo apt-get install -y ansible
    ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
