- name: Install containerd & kubeadm
  shell: |
    apt-get update
    apt-get install -y containerd
    modprobe overlay
    modprobe br_netfilter
    echo -e "overlay\nbr_netfilter" >> /etc/modules-load.d/k8s.conf
    echo -e "net.bridge.bridge-nf-call-iptables=1\nnet.ipv4.ip_forward=1" >> /etc/sysctl.d/k8s.conf
    sysctl --system
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubelet kubeadm kubectl

- name: Hole Join-Befehl vom Master (wird SSH vorausgesetzt!)
  shell: ssh -o StrictHostKeyChecking=no ubuntu@{{ hostvars['master'].inventory_hostname }} 'cat /home/ubuntu/join-command.sh' > /tmp/join.sh
  delegate_to: localhost

- name: Worker tritt Cluster bei
  command: bash /tmp/join.sh
