- name: Copy join script from master
  fetch:
    src: /home/ubuntu/join-command.sh
    dest: /tmp/join-command.sh
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Copy join script to worker
  copy:
    src: /tmp/join-command.sh
    dest: /home/ubuntu/join-command.sh
    mode: "0755"

- name: Execute join command
  command: bash /home/ubuntu/join-command.sh
