# roles/worker/tasks/main.yml

- name: Kubernetes Tools installieren (Worker)
  shell: |
    cd /tmp
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubeadm
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubelet
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
    install -o root -g root -m 0755 kubeadm /usr/local/bin/kubeadm
    install -o root -g root -m 0755 kubelet /usr/local/bin/kubelet
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    curl -sS https://raw.githubusercontent.com/kubernetes/release/v0.15.1/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service -o /etc/systemd/system/kubelet.service
    mkdir -p /etc/systemd/system/kubelet.service.d
    curl -sS https://raw.githubusercontent.com/kubernetes/release/v0.15.1/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf -o /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    systemctl daemon-reexec
    systemctl daemon-reload
    systemctl enable kubelet
    systemctl restart kubelet
  args:
    creates: /usr/local/bin/kubeadm

- name: Symlink für kubelet auf Worker erstellen
  file:
    src: /usr/local/bin/kubelet
    dest: /usr/bin/kubelet
    state: link
    force: true

- name: Systemd reload + kubelet neustarten
  systemd:
    name: kubelet
    enabled: true
    state: restarted
    daemon_reload: true

- name: Join-Skript vom Ansible Host auf Worker kopieren
  copy:
    src: /tmp/join-command.sh
    dest: /home/ubuntu/join-command.sh
    mode: 0755

- name: Cluster Join ausführen
  command: bash /home/ubuntu/join-command.sh

- name: Kubernetes Worker-Hostname herausfinden
  command: hostname
  register: worker_hostname

- name: Kubernetes Rolle 'worker' setzen
  shell: |
    kubectl label node {{ worker_hostname.stdout }} node-role.kubernetes.io/worker=worker --overwrite
  delegate_to: "{{ groups['master'][0] }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

