- name: SSH Public Key vom Master kopieren
  copy:
    src: /home/ubuntu/.ssh/id_rsa.pub
    dest: /home/ubuntu/.ssh/authorized_keys
    owner: ubuntu
    group: ubuntu
    mode: "0600"
  delegate_to: localhost

- name: Stelle sicher, dass kubelet vorhanden ist
  stat:
    path: /usr/local/bin/kubelet
  register: kubelet_bin

- name: Kubelet Pfad fixen wenn vorhanden
  file:
    src: /usr/local/bin/kubelet
    dest: /usr/bin/kubelet
    state: link
    force: yes
  when: kubelet_bin.stat.exists
  become: true

- name: Kubernetes-Komponenten manuell installieren (Worker)
  shell: |
    cd /tmp
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubeadm
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubelet
    curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl

    install -o root -g root -m 0755 kubeadm /usr/local/bin/kubeadm
    install -o root -g root -m 0755 kubelet /usr/local/bin/kubelet
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    curl -sS https://raw.githubusercontent.com/kubernetes/release/v0.15.1/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service -o /etc/systemd/system/kubelet.service
    mkdir -p /etc/systemd/system/kubelet.service.d
    curl -sS https://raw.githubusercontent.com/kubernetes/release/v0.15.1/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf -o /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

    systemctl daemon-reexec
    systemctl daemon-reload
    systemctl enable kubelet
    systemctl restart kubelet

- name: Warten auf Join-Skript vom Master
  wait_for:
    path: /home/ubuntu/join-command.sh
    timeout: 600

- name: Worker Node dem Cluster beitreten lassen
  command: bash /home/ubuntu/join-command.sh
