# .github/workflows/deploy-buenzli-shop.yml

name: Deploy Bünzli Shop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MASTER_IP: ${{ secrets.K8S_MASTER_PUBLIC_IP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$K8S_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          K8S_SSH_PRIVATE_KEY: ${{ secrets.K8S_SSH_PRIVATE_KEY }}

      - name: Upload Kubernetes YAMLs
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r k8s/ ubuntu@$MASTER_IP:/home/ubuntu/k8s/

      - name: Apply Kubernetes Resources
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$MASTER_IP << 'EOF'
            cd /home/ubuntu/k8s
            kubectl apply -f namespace.yaml
            kubectl apply -f secrets.yaml
            kubectl apply -f postgres-init-configmap.yaml
            kubectl apply -f postgres.yaml
            kubectl apply -f backend.yaml
            kubectl apply -f mailservice.yaml
            kubectl apply -f frontend.yaml
            kubectl apply -f admin.yaml
            kubectl apply -f ingress.yaml || echo "Kein Ingress installiert – weiter mit NodePort."
          EOF