name: Deploy Medusa

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.K8S_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.K8S_MASTER_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Run Medusa Deploy Playbook
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/deploy_medusa.yml
