name: Deploy Monitoring Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Prometheus & Grafana
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Setze kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > ~/.kube/config

      - name: Deploy Monitoring
        run: |
          kubectl apply -f k8s/prometheus-deployment.yml
          kubectl apply -f k8s/grafana-deployment.yml
