name: Deploy Medusa with Helm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Decode kubeconfig from Base64
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > kubeconfig
        chmod 600 kubeconfig

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Helm Upgrade/Install Medusa
      run: |
        helm upgrade --install mymedusa ./k8s/helm/medusa \
          -f ./k8s/helm/medusa/values.yaml \
          --kubeconfig $KUBECONFIG

    - name: Apply ClusterIssuer (cert-manager)
      run: |
        kubectl apply -f ./k8s/cluster-issuer.yaml --kubeconfig $KUBECONFIG

    - name: Check Pods
      run: kubectl get pods -A --kubeconfig $KUBECONFIG

    - name: Check Ingress
      run: kubectl get ingress -A --kubeconfig $KUBECONFIG
