name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_k8s_ssh_public_key: ${{ secrets.k8s_ssh_public_key }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials (mit Session Token)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply (Auto-Approve)
        run: terraform apply -auto-approve

      - name: Get Public IPs from Terraform
        id: get_ips
        run: |
          IPS=$(terraform output -json instance_public_ips | jq -r '.[]' | paste -sd "," -)
          echo "PUB_DNS=$IPS" >> $GITHUB_ENV

      - name: Create Ansible Inventory File
        run: |
          IFS=',' read -r MASTER WORKER1 WORKER2 <<< "$PUB_DNS"

          mkdir -p ../ansible
          echo "[master]" > ../ansible/inventory.ini
          echo "$MASTER ansible_user=ubuntu" >> ../ansible/inventory.ini

          echo "[worker]" >> ../ansible/inventory.ini
          echo "$WORKER1 ansible_user=ubuntu" >> ../ansible/inventory.ini
          echo "$WORKER2 ansible_user=ubuntu" >> ../ansible/inventory.ini

          echo "[all:vars]" >> ../ansible/inventory.ini
          echo "ansible_ssh_private_key_file=../terraform/ssh-key/id_rsa" >> ../ansible/inventory.ini

      - name: Write private SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.k8s_ssh_private_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          cd ../ansible
          ansible-playbook -i inventory.ini playbook.yml
