# === GitHub Actions Workflow: .github/workflows/deploy.yml ===

name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_k8s_ssh_public_key: ${{ secrets.K8S_SSH_PUBLIC_KEY }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials (mit Session Token)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply (Auto-Approve)
        run: terraform apply -auto-approve

      - name: Get Public IPs from Terraform
        id: get_ips
        run: |
          IPS=$(terraform output -json instance_public_ips | jq -r '.[]' | paste -sd "," -)
          echo "PUB_DNS=$IPS" >> $GITHUB_ENV

      - name: Write Private SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.K8S_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy SSH Public Key to all instances
        run: |
          PUBKEY="${{ secrets.K8S_SSH_PUBLIC_KEY }}"
          for ip in $(echo $PUB_DNS | tr "," "\n"); do
            echo " Waiting for SSH on $ip..."
            for i in {1..15}; do
              ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i ~/.ssh/id_rsa ubuntu@$ip "echo SSH ready" && break
              echo " Attempt $i: SSH not ready yet..."
              sleep 10
            done

            echo " Adding SSH public key to $ip (if not already present)..."
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$ip "\
              mkdir -p ~/.ssh && \
              grep -qxF \"$PUBKEY\" ~/.ssh/authorized_keys || echo \"$PUBKEY\" >> ~/.ssh/authorized_keys && \
              chmod 600 ~/.ssh/authorized_keys"
          done


      - name: Create Ansible Inventory File
        run: |
          IFS=',' read -r MASTER WORKER1 WORKER2 <<< "$PUB_DNS"

          mkdir -p ../ansible
          echo "[master]" > ../ansible/inventory.ini
          echo "$MASTER ansible_user=ubuntu" >> ../ansible/inventory.ini

          echo "[worker]" >> ../ansible/inventory.ini
          echo "$WORKER1 ansible_user=ubuntu" >> ../ansible/inventory.ini
          echo "$WORKER2 ansible_user=ubuntu" >> ../ansible/inventory.ini

          echo "[all:vars]" >> ../ansible/inventory.ini
          echo "ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../ansible/inventory.ini
          echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" >> ../ansible/inventory.ini
            - name: Setze MASTER_IP für späteren Zugriff
        id: extract_master_ip
        run: |
          IFS=',' read -r MASTER WORKER1 WORKER2 <<< "$PUB_DNS"
          echo "MASTER_IP=$MASTER" >> $GITHUB_ENV

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          cd ../ansible
          ansible-playbook -i inventory.ini playbook.yml

      - name: Debug: Zeige MASTER_IP
        run: echo "Master-IP: $MASTER_IP"

      - name: Fetch kubeconfig vom Master
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$MASTER_IP:/home/ubuntu/.kube/config kubeconfig
          base64 kubeconfig > kubeconfig.b64
          cat kubeconfig.b64

      - name: Lade kubeconfig.b64 als Artifact hoch
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig.b64

