name: Deploy Medusa

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.K8S_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.K8S_MASTER_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Generate dynamic inventory.ini
      run: |
        mkdir -p ansible
        echo "[master]" > ansible/inventory.ini
        echo "${{ secrets.K8S_MASTER_PUBLIC_IP }} ansible_user=ubuntu" >> ansible/inventory.ini

        echo "[all:vars]" >> ansible/inventory.ini
        echo "ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini
        echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" >> ansible/inventory.ini

        echo ""
        echo "Generated inventory.ini:"
        cat ansible/inventory.ini

    - name: 🚀 Run Medusa Deploy Playbook
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/deploy_medusa.yml
