name: Deploy Shop with Helm

on:
  push:
    branches:
      - main  # oder dein Deploy-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH for Git Clone
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.K8S_SSH_PRIVATE_KEY }}

    - name: Write kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.0

    - name: Clone Saleor Helm Chart
      run: |
        git clone git@github.com:saleor/helm-charts.git

    - name: Copy your custom values.yaml
      run: |
        cp ./k8s/helm/saleor/my-values.yaml ./helm-charts/charts/saleor/my-values.yaml

    - name: Helm Upgrade/Install Saleor
      run: |
        cd helm-charts/charts/saleor
        helm upgrade --install meinshop . -f my-values.yaml --kubeconfig $KUBECONFIG

    - name: Check Pods
      run: kubectl get pods -A --kubeconfig $KUBECONFIG

    - name: Check Services
      run: kubectl get svc -A --kubeconfig $KUBECONFIG
